name: Enforce Branch Policy
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  check-source-branch:
    runs-on: ubuntu-latest
 
    steps:
      - name: Validate source branch
        run: |
          echo "Source branch is ${{ github.head_ref }}"
 
          if [[ "${{ github.head_ref }}" != "dev" && "${{ github.head_ref }}" != "qa" ]]; then
            echo "❌ Only dev or qa branches can be merged into main."
            exit 1
          fi
 
          echo "✅ Branch is allowed"
